import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,Users,CalendarDays,BriefcaseBusiness,Plus,RefreshCw,BellRing,CheckCircle2,MapPin,Search,BarChart3} from 'lucide-react';
import {api,date,personName,RECRUITMENT_STAGES} from './api';
import {LineChart} from './referencePages';

const number=value=>Number(value||0).toLocaleString('ar-EG');
const stageColors={new:'#45bfff',review:'#a99aff',interview:'#ffb454',accepted:'#51dfcd',hired:'#71df9b',rejected:'#ff879a'};

export default function OverviewDashboard({focusRequest=0,version,officeId,nav=[],profileName,officesConfigured,alerts={},onAlert,onTab,onSelect,onCreate,onStage}){
  const [snapshot,setSnapshot]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[query,setQuery]=useState('');
  const searchRef=useRef(null);
  const allowed=key=>nav.some(item=>item[0]===key),canReports=allowed('reports'),canPeople=allowed('applicants');
  useEffect(()=>{if(focusRequest)searchRef.current?.focus();},[focusRequest]);
  useEffect(()=>{
    if(!canReports)return;
    const controller=new AbortController();setBusy(true);setError('');
    const params=new URLSearchParams();if(officeId)params.set('office_id',officeId);
    api('/dashboard?'+params,{signal:controller.signal}).then(data=>{if(!controller.signal.aborted)setSnapshot({officeId,data,updated:new Date()});}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});
    return()=>controller.abort();
  },[officeId,version,revision,canReports]);
  const current=snapshot?.officeId===officeId?snapshot:null,data=current?.data,m=data?.metrics||{},stages=data?.recruitment_stages||{};
  const value=v=>data?number(v):'—';
  const links=nav.filter(([key,label])=>key!=='overview'&&(!query||label.toLowerCase().includes(query.trim().toLowerCase())));
  const metricCards=[['إجمالي المتقدمين',m.total,'كل الطلبات المسجلة',Users,'applicants'],['طلبات اليوم',m.new_today,'طلبات وصلت اليوم بتوقيت القاهرة',Plus,null],['مقابلات اليوم',m.interviews_today,'المواعيد المجدولة اليوم',CalendarDays,'interviews'],['تم تعيينهم',m.hired,'وصلوا إلى مرحلة التعيين',BriefcaseBusiness,'hiring']];
  return <div className="ops-dashboard" dir="rtl">
    <header className="ops-welcome"><div><span className="ops-eyebrow">مساحة العمل / نظرة عامة</span><h1>كل خطوة توظيف، في مكان واحد.</h1><p>أهلًا {profileName}، تابع فريقك وابدأ بالخطوة الأهم اليوم.</p><span className="ops-scope"><MapPin size={13}/>{data?.selected_office?.name||(officeId?'المكتب المختار':'كل المكاتب المتاحة')}</span></div><div className="ops-welcome-actions">{canPeople&&officesConfigured&&<button className="ops-primary" onClick={onCreate}><Plus size={18}/> إضافة مرشح</button>}{canReports&&<button className="ops-secondary" onClick={()=>onTab('reports')}><BarChart3 size={17}/> عرض التقارير</button>}</div></header>
    <section className="ops-directory" aria-label="الوصول السريع"><div className="ops-directory-heading"><div><span className="ops-eyebrow">وصول سريع</span><h2>عايز تشتغل على إيه؟</h2></div><label className="ops-search"><Search size={17}/><input ref={searchRef} aria-label="ابحث في أدوات النظام" placeholder="ابحث في أدوات النظام…" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>Ctrl K</kbd></label></div><div className="ops-shortcuts">{links.map(([key,label,Icon])=><button key={key} onClick={()=>onTab(key)}><Icon size={19}/><span>{label}</span><ArrowLeft size={14}/></button>)}{!links.length&&<p role="status">مفيش أدوات بالاسم ده.</p>}</div></section>
    {canReports?<><div className="ops-section-title"><h2>نبض التوظيف</h2><div aria-live="polite"><span>{busy?'جارٍ تحديث البيانات…':current?'آخر تحديث '+current.updated.toLocaleTimeString('ar-EG',{hour:'2-digit',minute:'2-digit',timeZone:'Africa/Cairo'}):'البيانات غير متاحة'}</span><button className="ops-icon" aria-label="تحديث لوحة التحكم" disabled={busy} onClick={()=>setRevision(v=>v+1)}><RefreshCw size={16}/></button></div></div>
    {error&&<div className="ops-error" role="alert">تعذّر تحديث البيانات: {error}{data&&' · المعروض هو آخر تحديث ناجح.'}<button onClick={()=>setRevision(v=>v+1)}>إعادة المحاولة</button></div>}
    <div className="ops-metrics" aria-busy={busy}>{metricCards.map(([label,count,caption,Icon,target],i)=><article className={'ops-metric ops-tone-'+i} key={label}><div><span>{label}</span><Icon size={20}/></div><strong>{value(count)}</strong><footer><small>{caption}</small>{allowed(target)&&<button aria-label={'فتح '+label} onClick={()=>onTab(target)}><ArrowLeft size={16}/></button>}</footer></article>)}</div>
    <section className="ops-panel ops-pipeline"><header><div><h2>مسار التوظيف</h2><p>توزيع المرشحين حسب مرحلتهم الحالية</p></div><span>{value(m.active_candidates)} مرشح قيد المتابعة</span></header><div className="ops-stages">{Object.entries(RECRUITMENT_STAGES).map(([key,label],index)=><button key={key} disabled={!canPeople||!data} onClick={()=>onStage(key)} style={{'--stage-color':stageColors[key]}}><div><span className="ops-stage-index">{String(index+1).padStart(2,'0')}</span><ArrowLeft size={14}/></div><strong>{value(stages[key])}</strong><span>{label}</span><div className="ops-stage-track"><i style={{width:(m.total?Number(stages[key]||0)/m.total*100:0)+'%'}}/></div></button>)}</div></section>
    <div className="ops-grid"><section className="ops-panel"><header><div><h2>أداء التوظيف</h2><p>الطلبات والمقبولون من كل شهر تسجيل</p></div><span>آخر ٦ أشهر</span></header>{data?<LineChart data={data.growth||[]}/>:<div className="ops-empty">{busy?'جارٍ تحميل الأداء…':'بيانات الأداء غير متاحة'}</div>}</section><section className="ops-panel"><header><div><h2>مناطق العمل</h2><p>أكثر المناطق اختيارًا بين المتقدمين</p></div>{allowed('areas')&&<button onClick={()=>onTab('areas')} aria-label="إدارة مناطق العمل"><ArrowLeft size={17}/></button>}</header><div className="ops-areas">{(data?.area_distribution||[]).slice(0,5).map((area,i)=><div key={area.name}><span className="ops-area-rank">{i+1}</span><div><div><span>{area.name}</span><strong>{number(area.count)}</strong></div><div className="ops-area-track"><i style={{width:(area.count/Math.max(1,data.area_distribution[0].count)*100)+'%'}}/></div></div></div>)}{!data?.area_distribution?.length&&<div className="ops-empty">{data?'لسه مفيش مناطق مسجلة.':'بيانات المناطق غير متاحة'}</div>}</div></section></div>
    {canPeople&&<div className="ops-grid"><section className="ops-panel"><header><div><h2>أحدث المتقدمين</h2><p>افتح ملف المرشح لمتابعة بياناته ومحادثته</p></div><button onClick={()=>onTab('applicants')}>عرض الكل <ArrowLeft size={15}/></button></header><div className="ops-table-scroll"><table className="ops-table"><thead><tr><th>المرشح</th><th>منطقة العمل</th><th>الحالة</th><th><span className="ops-sr">الإجراء</span></th></tr></thead><tbody>{(data?.recent||[]).map(a=><tr key={a.id}><td><button className="ops-person" onClick={()=>onSelect(a.id)}><i>{personName(a)[0]}</i><span><strong>{personName(a)}</strong><small dir="ltr">{a.phone||'بدون رقم هاتف'}</small></span></button></td><td>{a.qualification?.preferred_work_area||'لم يحدد'}</td><td><span className="ops-badge" style={{'--stage-color':stageColors[a.recruitment_stage||'new']}}>{RECRUITMENT_STAGES[a.recruitment_stage||'new']||a.recruitment_stage}</span></td><td><button aria-label={'فتح ملف '+personName(a)} onClick={()=>onSelect(a.id)}><ArrowLeft size={16}/></button></td></tr>)}</tbody></table>{!data?.recent?.length&&<div className="ops-empty">{data?'أول طلب جديد هيظهر هنا.':'بيانات المرشحين غير متاحة'}</div>}</div></section><section className="ops-panel"><header><div><h2>المقابلات المجدولة</h2><p>آخر ٢٤ ساعة والمواعيد القادمة</p></div><button onClick={()=>onTab('interviews')} aria-label="عرض المقابلات"><CalendarDays size={18}/></button></header><div className="ops-list">{(data?.upcoming_interviews||[]).map(item=><button key={item.id} onClick={()=>item.applicant_id?onSelect(item.applicant_id):onTab('interviews')}><span className="ops-list-icon"><CalendarDays size={19}/></span><div><strong>{item.applicant_name||'مرشح'}</strong><small>{date(item.scheduled_at)}</small><small>{item.office?.name||'مكتب التوظيف'}</small></div><ArrowLeft size={16}/></button>)}{!data?.upcoming_interviews?.length&&<div className="ops-empty"><CalendarDays size={24}/><span>{data?'مفيش مقابلات مجدولة في الفترة دي.':'بيانات المقابلات غير متاحة'}</span></div>}</div></section></div>}
    </>:<div className="ops-panel ops-empty"><BarChart3 size={24}/><span>إحصائيات التوظيف متاحة للمستخدمين اللي عندهم صلاحية التقارير. تقدر تستخدم أدواتك من الوصول السريع.</span></div>}
    {canPeople&&<section className="ops-panel ops-attention"><header><div><h2><BellRing size={19}/> محتاج تدخلك</h2><p>تنبيهات كل المكاتب المتاحة لحسابك</p></div><span className="ops-badge">{number(alerts.open_count)} حالة مفتوحة</span></header><div className="ops-alerts">{(alerts.items||[]).slice(0,4).map(item=><button key={item.id} onClick={()=>onAlert(item)}><BellRing size={19}/><div><strong>{item.applicant_name||'متقدم يحتاج متابعة'}</strong><p>{item.body||'افتح الحالة لمراجعتها'}</p><small>{date(item.created_at)}</small></div><ArrowLeft size={17}/></button>)}{!alerts.items?.length&&<div className="ops-empty"><CheckCircle2 size={24}/><span>{alerts.configured===false?'مركز التنبيهات غير مفعّل.':'مفيش تنبيهات ظاهرة حاليًا.'}</span></div>}</div></section>}
  </div>;
}
