import 'dotenv/config';
import path from 'node:path';
import {database,createSerial} from './db.js';
import {WhatsAppManager} from './whatsapp-manager.js';
import {Worker} from './worker.js';
import {makeApi} from './api.js';
import {SpeechTranscriber} from './speech.js';
const db=database(),serial=createSerial();
const origins=(process.env.DASHBOARD_ORIGIN||'http://localhost:5173').split(',').map(x=>x.trim()).filter(Boolean);
if(process.env.RAILWAY_PUBLIC_DOMAIN)origins.push(`https://${process.env.RAILWAY_PUBLIC_DOMAIN}`);
const sessionPath=path.resolve(process.env.SESSION_PATH||'./sessions');
const speech=new SpeechTranscriber();
await speech.init();
let worker;
const connections=new WhatsAppManager({db,sessionPath,onMessage:record=>worker.receive(record)});
worker=new Worker({db,connections,serial,sessionPath,speech});
await worker.init();await connections.init();
const dashboardDist=process.env.DASHBOARD_DIST?path.resolve(process.env.DASHBOARD_DIST):null;
const app=makeApi({db,connections,worker,speech,serial,origins,dashboardDist});
const server=app.listen(Number(process.env.PORT)||3001,'0.0.0.0',()=>console.log('Speed Delivery recruitment service ready'));
async function shutdown(){worker.stop();server.close();await connections.close();process.exit(0);}
process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);
