import test from 'node:test';import assert from 'node:assert/strict';
import {phoneFromId,validateAnswer,computedStage,completion,csvCell,redactForAI} from '../src/domain.js';
import {planTurn} from '../src/flow.js';import {interpret} from '../src/ai.js';
const areas=[{id:'oct',name:'أكتوبر',active:true,details:'الشفت 9 ساعات. نقطة التجمع: المكتب.'},{id:'zayed',name:'الشيخ زايد',active:false,details:'تفاصيل متوقفة'}];
const questions=[{id:'name',field_key:'name',kind:'name',label:'اسمك بالكامل؟',position:1,active:true,required:true},{id:'area',field_key:'area',kind:'area',label:'أنهي منطقة؟',position:2,active:true,required:true},{id:'bike',field_key:'bike',kind:'yes_no',label:'معاك موتوسيكل؟',position:3,active:true,required:true}];
const settings={ai_enabled:true,welcome:'أهلاً',completion:'تم الاستلام'};
const applicant={stage:'new',answers:{},awaiting_id:null,bot_enabled:true};
const run=(a,text,extra={})=>planTurn({applicant:a,message:{body:text},questions,areas,settings,interpret:async()=>null,...extra});
test('LID is never displayed as a phone',()=>{assert.equal(phoneFromId('123456789012345@lid'),null);assert.equal(phoneFromId('201012345678@c.us'),'+201012345678');assert.equal(phoneFromId('123@g.us'),null);});
test('Arabic age and negative replies are validated',()=>{assert.equal(validateAnswer({kind:'number'},'عندي ٢٨ سنة',areas).value,28);assert.equal(validateAnswer({kind:'number'},'عندي ١٢٠ سنة',areas).ok,false);assert.equal(validateAnswer({kind:'yes_no'},'معنديش',areas).value,false);});
test('initial greeting asks first question without saving greeting',async()=>{const r=await run(applicant,'السلام عليكم');assert.equal(r.patch.awaiting_id,'name');assert.equal(r.patch.answers,undefined);});
test('answers are saved to their question with field key and progress',async()=>{const r=await run({...applicant,awaiting_id:'name'},'سيد محمد');assert.equal(r.patch.answers.name.value,'سيد محمد');assert.equal(r.patch.answers.name.key,'name');assert.equal(r.patch.stage,'incomplete');assert.equal(r.patch.awaiting_id,'area');});
test('area inquiry does not consume the pending answer',async()=>{const r=await run({...applicant,awaiting_id:'name'},'تفاصيل الشغل في اكتوبر؟');assert.match(r.reply,/الشفت 9 ساعات/);assert.equal(r.patch.answers,undefined);assert.equal(r.patch.awaiting_id,'name');});
test('first area inquiry remembers question to accept the next answer',async()=>{const r=await run(applicant,'تفاصيل اكتوبر');assert.equal(r.patch.awaiting_id,'name');});
test('unknown details never become free text answer',async()=>{const r=await run({...applicant,awaiting_id:'name'},'القبض كام؟');assert.match(r.reply,/تقصد أنهي منطقة/);assert.equal(r.patch.answers,undefined);});
test('disabled areas cannot be selected',()=>assert.equal(validateAnswer({kind:'area'},'الشيخ زايد',areas).ok,false));
test('AI can interpret indirect negative but cannot mark attendance',async()=>{const a={...applicant,awaiting_id:'bike',answers:{name:{value:'سيد محمد'},area:{value:'oct'}}};const r=await run(a,'لسه مجبتش موتوسيكل',{interpret:async()=>({intent:'answer',answer:'no',confidence:0.96})});assert.equal(r.patch.answers.bike.value,false);assert.equal(r.patch.stage,'complete');assert.equal(r.patch.awaiting_id,null);});
test('AI failure asks clarification without advancing',async()=>{const a={...applicant,awaiting_id:'bike',answers:{name:{value:'سيد محمد'},area:{value:'oct'}}};const r=await run(a,'رد مش مفهوم');assert.equal(r.patch.answers,undefined);assert.match(r.reply,/محتاج أوضح/);});
test('fake AI area IDs are rejected',async()=>{const a={...applicant,awaiting_id:'area',answers:{name:{value:'سيد محمد'}}};const r=await run(a,'مكان بعيد',{interpret:async()=>({intent:'answer',answer:'invented'})});assert.equal(r.patch.answers,undefined);});
test('stored false is a complete valid answer',()=>{const a={...applicant,answers:{name:{value:'سيد محمد'},area:{value:'oct'},bike:{value:false}}};assert.equal(completion(questions,a.answers,areas).complete,true);assert.equal(computedStage(a,questions,areas),'complete');});
test('changed question type invalidates stale answer without deleting it',()=>{const a={bike:{value:false,kind:'yes_no'}};assert.equal(completion([{...questions[2],kind:'image'}],a,areas).complete,false);});
test('manual stages stay protected',async()=>{for(const stage of ['lecture','working']){const a={...applicant,stage};assert.equal(computedStage(a,questions,areas),stage);assert.equal((await run(a,'اهلا')).reply,'');}});
test('human pause suppresses all bot responses',async()=>assert.equal((await run({...applicant,bot_enabled:false},'تفاصيل اكتوبر')).reply,''));
test('documents must have a stored attachment',()=>{assert.equal(validateAnswer({kind:'image'},'بعت الورق',areas).ok,false);assert.equal(validateAnswer({kind:'image'},'',areas,{path:'a/doc'}).value,'a/doc');});
test('optional question skip does not block completion',async()=>{const qs=[{...questions[0],required:false},questions[2]];const r=await run({...applicant,awaiting_id:'name'},'تخطي',{questions:qs});assert.equal(r.patch.answers.name.skipped,true);assert.equal(r.patch.awaiting_id,'bike');});
test('required question cannot be skipped',async()=>{const r=await run({...applicant,awaiting_id:'name'},'تخطي');assert.equal(r.patch.answers,undefined);});
test('CSV protects against spreadsheet formulas',()=>{assert.equal(csvCell('=1+1'),'"\'=1+1"');assert.equal(csvCell('سيد "محمد"'),'"سيد ""محمد"""');});
test('AI request redacts long phone/ID strings',()=>assert.ok(!redactForAI('رقمي ٠١٠١٢٣٤٥٦٧٨').includes('01012345678')));
test('AI invalid JSON and upstream errors fall back safely',async()=>{assert.equal(await interpret('hi',questions[0],areas,{key:'test',fetcher:async()=>({ok:false})}),null);assert.equal(await interpret('hi',questions[0],areas,{key:'test',fetcher:async()=>({ok:true,json:async()=>({candidates:[{content:{parts:[{text:'not json'}]}}]})})}),null);});

test('old bare LIDs are not migrated as phone numbers',async()=>{const {legacyPhone}=await import('../src/domain.js');assert.equal(legacyPhone('123456789012345'),null);assert.equal(legacyPhone('201012345678'),'+201012345678');});
test('previously skipped question is asked if changed to required',async()=>{const r=await run({...applicant,answers:{name:{skipped:true}},awaiting_id:null},'أهلا');assert.equal(r.patch.awaiting_id,'name');});
